// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDydrdZb77g9OJK1CbSgIyfrR8ZFkyZIsw',
    appId: '1:854866215223:web:34e0504f66cd695c5e1ab2',
    messagingSenderId: '854866215223',
    projectId: 'crud-9238d',
    authDomain: 'crud-9238d.firebaseapp.com',
    storageBucket: 'crud-9238d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBp4q8Eb2GIlKHYj2YwAxp12K48Nt7YjY',
    appId: '1:854866215223:android:9bfc8eef06c2c64f5e1ab2',
    messagingSenderId: '854866215223',
    projectId: 'crud-9238d',
    storageBucket: 'crud-9238d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq9th1hlplF2XYRyAzkSU_mMEIEOXiMUw',
    appId: '1:854866215223:ios:640586eb8d9677e15e1ab2',
    messagingSenderId: '854866215223',
    projectId: 'crud-9238d',
    storageBucket: 'crud-9238d.appspot.com',
    iosClientId: '854866215223-16dr590nh57vjjnda3n7ppvkb3uu56pq.apps.googleusercontent.com',
    iosBundleId: 'com.mg.firebase.crud.firebaseCrud',
  );
}
